# Generated by Django 3.1.1 on 2022-12-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('EMP_ID', models.CharField(help_text='EMP_ID', max_length=20, primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=100)),
                ('POST', models.CharField(max_length=20)),
                ('SALARY', models.IntegerField()),
            ],
        ),
    ]
